data:
  test_size: 0.2
  random_state: 42

model:
  type: RandomForestRegressor
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  random_state: 42

features:
  - property_size
  - bedrooms
  - bathrooms
  - location_encoded